    # Example docker-compose.yml for Astro with a headless CMS
    version: '3.8'

    services:
      astro-app:
        build: . # Builds from the Dockerfile in the current directory
        ports:
          - "8080:80"
        depends_on:
          - headless-cms # If your Astro app needs to fetch data from the CMS

      headless-cms:
        image: wordpress:latest # Or strapi/strapi, directus/directus, etc.
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - wordpress_data:/var/www/html

      db:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        volumes:
          - db_data:/var/lib/mysql

    volumes:
      wordpress_data:
      db_data:
